title: Seoyoung Kim
description: Researcher in Architecture and Urban AI
author: Seoyoung Kim
avatar: /logo.png
email: seoyoungkim0124@yonsei.ac.kr

# 2. 필수 추가 항목 (원래 파일에 빠져있으므로 plugins 위에 추가 필요)
url: "https://seoyoung-git.github.io"
baseurl: ""

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.png
social:
  name: Seoyoung Kim
  links:
    - https://github.com/seoyoung-git
    - https://www.laudyonsei.com/
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
